# -*- coding: utf-8 -*-
"""F1_ LapData_Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Kp2SuUavBF3JTZmAgv6Qx2GKoCCEmuo
"""

# Lap data format: [Sector1, Sector2, Sector3]
lap_times = [
    [25.0, 30.0, 37.0],  # Lap 1
    [30.0, 45.0, 48.0],  # Lap 2
    [20.0, 40.0, 25.0]   # Lap 3
]

# Calculate total times
total_times = [sum(lap) for lap in lap_times]

print("Total lap times:")
for i, t in enumerate(total_times):
    print(f"Lap {i+1}: {t:.2f} sec")

average_time = sum(total_times) / len(total_times)
fastest_time = min(total_times)

print(f"\nAverage Lap Time: {average_time:.2f} sec")
print(f"Fastest Lap Time: {fastest_time:.2f} sec")

print("\nDelta to Fastest Lap:")
for i, t in enumerate(total_times):
    delta = t - fastest_time
    print(f"Lap {i+1}: +{delta:.2f} sec")

import matplotlib.pyplot as plt

# X-axis: Lap numbers
lap_numbers = list(range(1, len(total_times) + 1))

# Y-axis: Total lap times
plt.plot(lap_numbers, total_times, marker='o', linestyle='-', color='blue')

# Labels and title
plt.title("Lap Time Trend")
plt.xlabel("Lap Number")
plt.ylabel("Lap Time (sec)")

# Show grid and plot
plt.grid(True)
plt.show()

# 📥 Input: Number of Laps and Sector Times
num_laps = int(input("Enter number of laps: "))
lap_times = []

for i in range(num_laps):
    print(f"\nEnter sector times for Lap {i+1}:")
    s1 = float(input("  Sector 1 time: "))
    s2 = float(input("  Sector 2 time: "))
    s3 = float(input("  Sector 3 time: "))
    lap_times.append([s1, s2, s3])

# 🧮 Total Lap Times
total_times = [sum(lap) for lap in lap_times]

print("\nTotal lap times:")
for i, t in enumerate(total_times):
    print(f"Lap {i+1}: {t:.2f} sec")

# 📊 Average + Fastest Lap Calculation
average_time = sum(total_times) / len(total_times)
fastest_time = min(total_times)
fastest_lap_index = total_times.index(fastest_time)

print(f"\nAverage Lap Time: {average_time:.2f} sec")
print(f"Fastest Lap Time: {fastest_time:.2f} sec (Lap {fastest_lap_index + 1})")

# 🧠 Delta to Fastest Lap
print("\nDelta to Fastest Lap:")
for i, t in enumerate(total_times):
    delta = t - fastest_time
    print(f"Lap {i+1}: +{delta:.2f} sec")

# 📈 Plot: Lap Time Trend with Fastest Highlighted
import matplotlib.pyplot as plt

lap_numbers = list(range(1, len(total_times) + 1))

plt.figure(figsize=(8, 5))
plt.plot(lap_numbers, total_times, marker='o', linestyle='-', color='blue', label='Lap Times')

# 🟢 Highlight the Fastest Lap
plt.scatter(lap_numbers[fastest_lap_index], fastest_time, color='green', s=100, label='Fastest Lap')

plt.title("Lap Time Trend")
plt.xlabel("Lap Number")
plt.ylabel("Lap Time (sec)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()